from dataclasses import dataclass


@dataclass
class Client:
    name: str
    role: str
    logo: str
    project: str
    url: str


CLIENTS = [
    Client(name='NRK',
           role='Filming & Editing',
           logo='img/clients/nrk.png',
           project='Filming and editing Forskerstandup 2017',
           url='https://nrk.no'),
    Client(name='TV2 Sumo',
           role='Audio',
           logo='img/clients/tv2.png',
           project='Siddis brass student production',
           url='https://tv2.no'),
    Client(name='Oilers',
           role='Directing, VMIX, Replay opeartor, PTZ, Video',
           logo='img/clients/oilers.png',
           project='Live production for Stavanger Oilers',
           url='https://oilers.no'),
    Client(name='Klippen Lydsystemer',
           role='Camera operator, rigging',
           logo='img/clients/kls.png',
           project='Events and concerts',
           url='https://kls.no'),
    Client(name='IMI-Media',
           role='Oilers',
           logo='img/clients/imi.png',
           project='See Oilers',
           url='https://imikirken.no'),
    Client(name='Eventi',
           role='AV-technician',
           logo='img/clients/eventi.png',
           project='AV work',
           url='https://eventi.no'),
    Client(name='Easee',
           role='Photography',
           logo='img/clients/easee.png',
           project='Product photography',
           url='https://easee.com'),
    Client(name='Smartly / SEDevices',
           role='Photography',
           logo='img/clients/smartly.png',
           project='Product photography',
           url='https://smartly.no'),
    Client(name='Rogaland Fylkeskommune',
           role='AV technician & video',
           logo='img/clients/rogfk.png',
           project='Videos and live productions',
           url='https://rogfk.no'),
    Client(name='Norwegian Academy of Music',
           role='Video documentation',
           logo='img/clients/nmh.png',
           project='Video documentation of concerts',
           url='https://nmh.no'),
    Client(name='Kåkå Kverulantkatedralen',
           role='Video production',
           logo='img/clients/kåkå.png',
           project='Kåkånomics 2017-2018',
           url='https://kaakaa.no/'),
    Client(name='Filmavdelingen',
           role='Camera operator',
           logo='img/clients/filmavdelingen.png',
           project='Conference work',
           url='https://filmavdelingen.no'),
    Client(name='Sandviks',
           role='Podcast technician',
           logo='img/clients/sandviks.png',
           project='Babyverden.no Podcast',
           url='https://babyverden.no'),
    Client(name='Vau.fi',
           role='Podcast technician',
           logo='img/clients/vaufi.png',
           project='Vau.fi Podcast',
           url='https://vau.fi'),
    Client(name='University of Stavanger',
           role='Content production',
           logo='img/clients/uis.png',
           project='Content production & podcasts for UiS',
           url='https://uis.no'),
    Client(name='University of Oslo',
           role='Content production',
           logo='img/clients/uio.png',
           project='The Gynecologist\'s Saloon podcast & flipped classroom',
           url='https://uio.no'),
    Client(name='NEP',
           role='Camera operator',
           logo='img/clients/nep.png',
           project='Conference work',
           url='https://www.nepnorway.com/'),
    Client(name='Lura IL',
           role='Content production',
           logo='img/clients/lurail.png',
           project='Advertising videos',
           url='#'),
    Client(name='Statsbygg',
           role='Content production',
           logo='img/clients/statsbygg.png',
           project='Advertising videos',
           url='https://www.statsbygg.no/'),
    Client(name='Siglar',
           role='Content production',
           logo='img/clients/siglar.png',
           project='Advertising videos',
           url='https://www.siglarcarbon.com/'),
    Client(name='Studioevent',
           role='Audio Engineer',
           logo='img/clients/studioevent.png',
           project='Music studio work',
           url='https://studioevent.no'),
    Client(name='Nuart',
           role='Content production',
           logo='img/clients/nuart.png',
           project='Documentation videos',
           url='https://nuart.no'),
    Client(name='Sølvberget',
           role='Video documentation',
           logo='img/clients/solvberget.png',
           project='Conference work',
           url='https://solvberget.no')
]
